### PR TITLE
Switch to instance

### PR DESCRIPTION
**Pull request by tmaytff**

### CODE REVIEW

**Comment by tmaytff** [comment]
@ktvtff please take a look at proposed v1.1

Moved away from static methods and make static serverIdAsHex so as to not continually recalculate same value.

Now, a user can create several instances on same machine with different serverId.  Not sure why they would, but they can.

Question, will recursive call to "synchronized" method block itself ?   I'd imagine not, since I think you tested it, and the semaphore likely references the thread.

**Comment by ktvtff** [comment]
Makes sense - that simplifies a lot of the structure.

I'll do some testing on the synchronized method.

**Comment by ktvtff** [comment]
Verified that the recursive synchronized call doesn't block itself.

I did some testing with 300 overlapping threads each generating 5000 ids. The counter maxed out around 140, and I verified that it didn't produce any duplicates in the entire run.

Lowering the counter max to 100 runs a bit slower because it hits the sleep call regularly, but still doesn't generate any duplicates.

**Comment by ktvtff** [comment]
I think this looks good. Any other changes you want to make, or shall I merge it & release 1.1?

**Pull request merged**
